from itn_numeric import apply_numeric_itn

CASES = {
    # Numeric v1 regression cases
    "版本是一点七": "版本是1.7",
    "总共有三十八个文件": "总共有38个文件",
    "一百零二": "102",
    "二零二六": "2026",
    "零一二三": "0123",
    "零零一二三": "00123",
    "幺": "1",
    "幺二三": "123",
    "零幺二三": "0123",
    "编号零幺二三": "编号0123",
    "零幺点零二": "01.02",
    "零一二三四五六七八九十": "012345678910",
    "一二三四五六七八九": "123456789",
    "一二三四五六七八九十": "12345678910",
    "负三点五": "-3.5",
    "万一失败就重试": "万一失败就重试",
    "一点问题都没有": "一点问题都没有",
    "there are thirty eight files": "there are 38 files",
    "one hundred and two": "102",
    "version one point seven": "version 1.7",
    "minus three point five": "-3.5",

    # Percent / per-mille / per-myriad
    "百分之三十八": "38%",
    "百分之一": "1%",
    "百分之零点五": "0.5%",
    "负百分之三点五": "-3.5%",
    "千分之一": "1‰",
    "千分之十二点五": "12.5‰",
    "万分之一": "1‱",
    "万分之三点五": "3.5‱",
    "百分位排名": "百分位排名",
    "千分位分隔符": "千分位分隔符",
    "增长了三个百分点": "增长了3个百分点",
    "这里只写百分之": "这里只写百分之",
    "thirty eight percent": "38%",
    "one point five per cent": "1.5%",
    "two per mille": "2‰",
    "three per ten thousand": "3‱",

    # Currency v2 regression
    "三十八美元": "USD 38",
    "一点五欧元": "EUR 1.5",
    "二十英镑": "GBP 20",
    "一千日元": "JPY 1000",
    "人民币三十八元": "CNY 38",
    "三十八人民币": "CNY 38",
    "五十新加坡元": "SGD 50",
    "一百港元": "HKD 100",
    "二百澳元": "AUD 200",
    "三百加元": "CAD 300",
    "四十瑞士法郎": "CHF 40",
    "五万韩元": "KRW 50000",
    "六百新台币": "TWD 600",
    "七十新西兰元": "NZD 70",
    "八百印度卢比": "INR 800",
    "nine US dollars": "USD 9",
    "ten euros": "EUR 10",
    "twenty British pounds": "GBP 20",
    "one hundred Japanese yen": "JPY 100",
    "fifty Chinese yuan": "CNY 50",
    "sixty Singapore dollars": "SGD 60",
    "三十八元": "38元",
    "人民币汇率": "人民币汇率",
    "thirty eight pounds": "38 pounds",
    "thirty eight dollars": "38 dollars",

    # Temperature
    "三十摄氏度": "30°C",
    "摄氏三十度": "30°C",
    "零下五摄氏度": "-5°C",
    "摄氏零下五度": "-5°C",
    "华氏六十八度": "68°F",
    "零下四十华氏度": "-40°F",
    "三百开尔文": "300 K",
    "thirty degrees Celsius": "30°C",
    "minus forty degrees Fahrenheit": "-40°F",
    "three hundred kelvin": "300 K",

    # Mass / length
    "三公斤": "3 kg",
    "三千克": "3 kg",
    "二点五吨": "2.5 t",
    "五百毫克": "500 mg",
    "三微克": "3 μg",
    "二十纳克": "20 ng",
    "五磅": "5 lb",
    "十二盎司": "12 oz",
    "三公里": "3 km",
    "三千米": "3 km",
    "二百厘米": "200 cm",
    "五毫米": "5 mm",
    "十微米": "10 μm",
    "七纳米": "7 nm",
    "三英尺": "3 ft",
    "十二英寸": "12 in",
    "five kilograms": "5 kg",
    "two point five tonnes": "2.5 t",
    "three milligrams": "3 mg",
    "ten micrograms": "10 μg",
    "five kilometers": "5 km",
    "two hundred centimeters": "200 cm",
    "three feet": "3 ft",
    "twelve inches": "12 in",

    # Area / volume
    "三平方米": "3 m²",
    "二平方公里": "2 km²",
    "五百平方厘米": "500 cm²",
    "十公顷": "10 ha",
    "三英亩": "3 acre",
    "五亩": "5 亩",
    "二立方米": "2 m³",
    "三百立方厘米": "300 cm³",
    "一点五升": "1.5 L",
    "五百毫升": "500 mL",
    "三微升": "3 μL",
    "two square meters": "2 m²",
    "three square kilometers": "3 km²",
    "five hectares": "5 ha",
    "two cubic meters": "2 m³",
    "five hundred milliliters": "500 mL",

    # Speed / acceleration / flow
    "一百公里每小时": "100 km/h",
    "二十米每秒": "20 m/s",
    "九点八米每秒平方": "9.8 m/s²",
    "五节": "5 kn",
    "三升每分钟": "3 L/min",
    "二立方米每秒": "2 m³/s",
    "one hundred kilometers per hour": "100 km/h",
    "twenty meters per second": "20 m/s",
    "nine point eight meters per second squared": "9.8 m/s²",
    "five knots": "5 kn",
    "three liters per minute": "3 L/min",

    # Force / torque / pressure
    "十牛顿": "10 N",
    "三千牛": "3 kN",
    "二兆牛顿": "2 MN",
    "五毫牛顿": "5 mN",
    "十二牛顿米": "12 N·m",
    "三千牛顿米": "3 kN·m",
    "一百零一点三千帕": "101.3 kPa",
    "二兆帕": "2 MPa",
    "一点二标准大气压": "1.2 atm",
    "七百六十毫米汞柱": "760 mmHg",
    "三十磅每平方英寸": "30 psi",
    "ten newtons": "10 N",
    "three kilonewtons": "3 kN",
    "twelve newton meters": "12 N·m",
    "one hundred one point three kilopascals": "101.3 kPa",
    "two megapascals": "2 MPa",
    "one point two atmospheres": "1.2 atm",
    "seven hundred sixty millimeters of mercury": "760 mmHg",
    "thirty pounds per square inch": "30 psi",

    # Energy / power / frequency
    "五千焦": "5 kJ",
    "二兆焦": "2 MJ",
    "三百千卡": "300 kcal",
    "十千瓦时": "10 kWh",
    "三度电": "3 kWh",
    "二百电子伏特": "200 eV",
    "一点五千瓦": "1.5 kW",
    "三兆瓦": "3 MW",
    "六十赫兹": "60 Hz",
    "二点四吉赫": "2.4 GHz",
    "five kilojoules": "5 kJ",
    "two megajoules": "2 MJ",
    "three hundred kilocalories": "300 kcal",
    "ten kilowatt hours": "10 kWh",
    "one point five kilowatts": "1.5 kW",
    "sixty hertz": "60 Hz",
    "two point four gigahertz": "2.4 GHz",

    # Electrical / magnetic / photometric
    "五伏特": "5 V",
    "十二千伏": "12 kV",
    "二安培": "2 A",
    "三百毫安": "300 mA",
    "十千欧": "10 kΩ",
    "二点二兆欧": "2.2 MΩ",
    "一百微法": "100 μF",
    "十毫亨": "10 mH",
    "三特斯拉": "3 T",
    "五百流明": "500 lm",
    "二百勒克斯": "200 lx",
    "five volts": "5 V",
    "twelve kilovolts": "12 kV",
    "two amperes": "2 A",
    "three hundred milliamps": "300 mA",
    "ten kiloohms": "10 kΩ",
    "one hundred microfarads": "100 μF",
    "three teslas": "3 T",

    # Chemistry / concentration / molar quantities
    "三摩尔": "3 mol",
    "五毫摩尔": "5 mmol",
    "二微摩尔": "2 μmol",
    "零点五摩尔每升": "0.5 mol/L",
    "三毫摩尔每升": "3 mmol/L",
    "十八克每摩尔": "18 g/mol",
    "五毫克每升": "5 mg/L",
    "二微克每毫升": "2 μg/mL",
    "three moles": "3 mol",
    "five millimoles": "5 mmol",
    "zero point five moles per liter": "0.5 mol/L",
    "three millimoles per litre": "3 mmol/L",
    "eighteen grams per mole": "18 g/mol",
    "five milligrams per liter": "5 mg/L",

    # Density / angle
    "一千千克每立方米": "1000 kg/m³",
    "一点二克每立方厘米": "1.2 g/cm³",
    "三弧度": "3 rad",
    "二球面度": "2 sr",
    "one thousand kilograms per cubic meter": "1000 kg/m³",
    "one point two grams per cubic centimeter": "1.2 g/cm³",
    "three radians": "3 rad",
    "ninety degrees": "90°",

    # Ambiguity guards
    "温度三十度": "温度30°C",
    "温度是三十度": "温度是30°C",
    "气温零下五度": "气温-5°C",
    "九十度角": "90度角",  # Bare 度 remains ambiguous outside a temperature context.
    "花了三英镑": "花了GBP 3",     # explicit currency beats lb
    "paid three pounds": "paid 3 pounds",  # bare pounds remains ambiguous
    "用了三加仑水": "用了三加仑水",  # unspecified US/imperial gallon remains unchanged
    "别出幺蛾子": "别出幺蛾子",
    "他是家里的老幺": "他是家里的老幺",

    # Date / time v4 — Chinese calendar dates
    "二零二六年八月八日": "2026-08-08",
    "二零二六年幺月幺日": "2026-01-01",
    "二〇二六年十二月三十一号": "2026-12-31",
    "二千零二十六年一月二日": "2026-01-02",
    "2026年8月8日": "2026-08-08",
    "八月八日": "8月8日",
    "十二月三十一号": "12月31日",
    "二零二六年八月": "2026-08",
    "2026年12月": "2026-12",
    "今天": "今天",
    "明天": "明天",
    "后天": "后天",
    "昨天": "昨天",
    "前天": "前天",

    # Date / time v4 — Chinese clock expressions
    "下午三点半": "15:30",
    "下午幺点": "13:00",
    "上午九点一刻": "09:15",
    "晚上八点三刻": "20:45",
    "三点半": "03:30",
    "三点一刻": "03:15",
    "三点三刻": "03:45",
    "三点三十分": "03:30",
    "十五点三十分": "15:30",
    "三点二十分三十秒": "03:20:30",
    "下午三点二十分三十秒": "15:20:30",
    "下午三点零五": "15:05",
    "上午十二点": "00:00",
    "中午十二点": "12:00",
    "中午一点": "13:00",
    "下午十二点": "12:00",
    "晚上十二点": "00:00",
    "凌晨一点": "01:00",
    "凌晨十二点": "00:00",
    "早上七点": "07:00",
    "下午3:05": "15:05",
    "下午3:05:09": "15:05:09",
    "三点钟": "03:00",
    "十五点整": "15:00",
    "三点问题": "三点问题",
    "三点零五": "3.05",
    "二零二六年八月八日下午三点半": "2026-08-08 15:30",
    "八月八日下午三点半": "8月8日 15:30",
    "明天下午三点": "明天 15:00",
    "今天上午九点一刻": "今天 09:15",

    # Date / time v4 — English calendar dates
    "August eighth, 2026": "2026-08-08",
    "August 8th, 2026": "2026-08-08",
    "8th August 2026": "2026-08-08",
    "the eighth of August 2026": "2026-08-08",
    "August twenty-first, twenty twenty-six": "2026-08-21",
    "February twenty ninth, twenty twenty four": "2024-02-29",
    "August eighth": "Aug 8",
    "the first of January": "Jan 1",
    "December thirty-first, nineteen ninety nine": "1999-12-31",
    "January first, two thousand and one": "2001-01-01",

    # Date / time v4 — English clock expressions
    "3:30 PM": "15:30",
    "3:05 a.m.": "03:05",
    "15:30": "15:30",
    "15:30:45": "15:30:45",
    "three thirty pm": "15:30",
    "three oh five am": "03:05",
    "three pm": "15:00",
    "twelve am": "00:00",
    "twelve pm": "12:00",
    "three o'clock": "03:00",
    "three o'clock p.m.": "15:00",
    "half past three": "03:30",
    "quarter past three": "03:15",
    "a quarter to four": "03:45",
    "three thirty in the afternoon": "15:30",
    "nine in the morning": "09:00",
    "eight in the evening": "20:00",
    "twelve at night": "00:00",
    "three thirty at night": "03:30",
    "eight at night": "20:00",
    "at three thirty": "at 03:30",
    "around nine fifteen": "around 09:15",
    "noon": "12:00",
    "midnight": "00:00",
    "August eighth, 2026 at three thirty pm": "2026-08-08 at 15:30",
    "the eighth of August 2026 at nine fifteen am": "2026-08-08 at 09:15",

    # Date / time v4 — durations (no calendar arithmetic)
    "三小时": "3 h",
    "两个小时": "2 h",
    "二十分钟": "20 min",
    "五秒": "5 s",
    "一百毫秒": "100 ms",
    "三微秒": "3 μs",
    "两天": "2 d",
    "三周": "3 wk",
    "三个星期": "3 wk",
    "三小时二十分钟五秒": "3 h 20 min 5 s",
    "three hours": "3 h",
    "twenty minutes": "20 min",
    "five seconds": "5 s",
    "one hundred milliseconds": "100 ms",
    "three microseconds": "3 μs",
    "two days": "2 d",
    "three weeks": "3 wk",
    "three hours twenty minutes five seconds": "3 h 20 min 5 s",
}

for src, expected in CASES.items():
    got = apply_numeric_itn(src)
    assert got == expected, f"{src!r}: expected {expected!r}, got {got!r}"
    print(f"OK  {src}  ->  {got}")

print(f"All {len(CASES)} ITN tests passed.")
